# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/src/*/.github/workflows'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10

  - package-ecosystem: 'composer'
    directories:
      - '/'
      - '/tools'
    schedule:
      interval: 'daily'
