name: Markdown Lint

on:
  push:
    branches:
      - 1.x
    paths:
      - '**/*.md'
      - .github/workflows/markdown.yml
      - .markdownlint-cli2.yaml
  pull_request:
    branches:
      - 1.x
    paths:
      - '**/*.md'
      - .github/workflows/markdown.yml
      - .markdownlint-cli2.yaml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  markdownlint:
    name: Lint markdown
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
